"""
Summarizer & Q&A Engine for Research & Document Summarization Agent.
Wraps Gemini API using google-genai / google-generativeai SDKs for document summaries, key points, Q&A, and insights.
"""

import os
from typing import Dict, Any, List, Optional, Tuple

NEW_SDK_AVAILABLE = False
LEGACY_SDK_AVAILABLE = False

# Try importing the new unified google-genai SDK first
try:
    from google import genai
    from google.genai import types
    NEW_SDK_AVAILABLE = True
except ImportError:
    pass

# Try importing legacy google-generativeai SDK
try:
    import google.generativeai as legacy_genai
    LEGACY_SDK_AVAILABLE = True
except ImportError:
    pass



class GeminiSummarizer:
    """
    Unified client wrapper for Google Gemini API providing Document Summarization,
    Key Point Extraction, Contextual Document Q&A, and Analytics Insights.
    """

    SUPPORTED_MODELS = [
        "gemini-2.5-flash",
        "gemini-1.5-flash",
        "gemini-2.0-flash",
        "gemini-1.5-pro"
    ]

    def __init__(self, api_key: Optional[str] = None, model_name: str = "gemini-2.5-flash"):
        """
        Initialize Gemini client with API key and target model.
        
        Args:
            api_key: Gemini API key string.
            model_name: Selected Gemini model name.
        """
        self.api_key = api_key or os.getenv("GEMINI_API_KEY")
        if not self.api_key:
            raise ValueError(
                "Gemini API Key is missing. Please enter your API key in the sidebar "
                "or configure GEMINI_API_KEY in your environment / .env file."
            )

        self.model_name = model_name if model_name in self.SUPPORTED_MODELS else "gemini-2.5-flash"
        self._setup_client()

    def _setup_client(self):
        """Set up client connection for either new SDK or legacy SDK."""
        if NEW_SDK_AVAILABLE:
            self.client = genai.Client(api_key=self.api_key)
            self.sdk_mode = "new"
        elif LEGACY_SDK_AVAILABLE:
            legacy_genai.configure(api_key=self.api_key)
            self.legacy_model = legacy_genai.GenerativeModel(self.model_name)
            self.sdk_mode = "legacy"
        else:
            raise ImportError(
                "Neither 'google-genai' nor 'google-generativeai' package is installed. "
                "Please run `pip install google-genai` or `pip install google-generativeai`."
            )

    def _generate_text(self, prompt: str, system_instruction: Optional[str] = None) -> str:
        """Internal helper to dispatch prompt execution to the active Gemini SDK."""
        try:
            if self.sdk_mode == "new":
                config = types.GenerateContentConfig(
                    temperature=0.2,
                    top_p=0.95,
                    system_instruction=system_instruction
                ) if system_instruction else types.GenerateContentConfig(temperature=0.2, top_p=0.95)

                response = self.client.models.generate_content(
                    model=self.model_name,
                    contents=prompt,
                    config=config
                )
                return response.text.strip() if response.text else "No response generated by model."
            else:
                full_prompt = f"System Instruction: {system_instruction}\n\n{prompt}" if system_instruction else prompt
                response = self.legacy_model.generate_content(
                    full_prompt,
                    generation_config=legacy_genai.types.GenerationConfig(temperature=0.2)
                )
                return response.text.strip() if response.text else "No response generated by model."
        except Exception as e:
            err_msg = str(e)
            if "API_KEY_INVALID" in err_msg or "invalid API key" in err_msg.lower():
                raise ValueError("Invalid Gemini API Key provided. Please verify your API key.")
            elif "RESOURCE_EXHAUSTED" in err_msg or "quota" in err_msg.lower():
                raise RuntimeError("Gemini API rate limit or quota exceeded. Please wait a moment or switch model.")
            else:
                raise RuntimeError(f"Error calling Gemini API ({self.model_name}): {err_msg}")

    def generate_summary(
        self,
        document_text: str,
        summary_style: str = "Executive Summary",
        custom_instructions: str = ""
    ) -> str:
        """
        Generate document summary according to chosen style.
        
        Args:
            document_text: Extracted full text.
            summary_style: Selected summary style mode.
            custom_instructions: Optional user prompt customization.
            
        Returns:
            Markdown formatted summary text.
        """
        style_prompts = {
            "Executive Summary": (
                "Provide a comprehensive, high-level Executive Summary. "
                "Structure it into: 📌 Executive Overview, 🎯 Strategic Significance, "
                "💡 Core Findings, and 🚀 Next Steps/Conclusion."
            ),
            "Detailed Technical Summary": (
                "Provide an in-depth, detailed technical summary. "
                "Break down methodologies, data points, architectural/theoretical concepts, "
                "key metrics, and detailed findings."
            ),
            "Actionable Bullet Points": (
                "Summarize the entire document into concise, high-impact actionable bullet points. "
                "Group points logically into major subheadings."
            ),
            "TL;DR Quick Overview": (
                "Provide an ultra-concise 3 to 4 sentence TL;DR summary capturing "
                "the single most important takeaway and essence of the document."
            )
        }

        selected_prompt = style_prompts.get(summary_style, style_prompts["Executive Summary"])
        
        system_instruction = (
            "You are an expert research analyst and technical communicator. "
            "Synthesize document content with precision, objective accuracy, clarity, and clean formatting."
        )

        prompt = f"""
{selected_prompt}

{f"Additional User Instructions: {custom_instructions}" if custom_instructions else ""}

--- DOCUMENT CONTENT ---
{document_text}
--- END DOCUMENT CONTENT ---
"""
        return self._generate_text(prompt, system_instruction=system_instruction)

    def extract_key_points(self, document_text: str) -> str:
        """
        Extract key highlights, takeaways, and topics from document text.
        
        Args:
            document_text: Document text string.
            
        Returns:
            Markdown formatted key takeaways and topic tags.
        """
        system_instruction = "You are a research intelligence agent extracting structured key findings."

        prompt = f"""
Analyze the document provided below and extract:
1. 🌟 Top 5 Crucial Takeaways (numbered list with bold headers).
2. 🔑 Core Concepts & Terminology (bullet points with brief definitions).
3. 🏷️ Primary Domain Tags / Keywords (formatted as inline code tags, e.g. `#MachineLearning`, `#DataPrivacy`).
4. ⚠️ Potential Limitations, Risks, or Gaps mentioned.

--- DOCUMENT CONTENT ---
{document_text}
--- END DOCUMENT CONTENT ---
"""
        return self._generate_text(prompt, system_instruction=system_instruction)

    def answer_question(
        self,
        document_text: str,
        question: str,
        chat_history: Optional[List[Dict[str, str]]] = None
    ) -> str:
        """
        Answer user questions strictly based on the document text.
        
        Args:
            document_text: Full document text context.
            question: User's question string.
            chat_history: Optional prior chat history list [{'role': 'user'/'assistant', 'content': '...'}].
            
        Returns:
            Answer string with grounding citations/excerpts.
        """
        system_instruction = (
            "You are an AI Document Q&A Assistant. Answer questions strictly based on the provided document text. "
            "If the answer cannot be determined from the document, state clearly: "
            "'I cannot find the answer to this question in the uploaded document.' "
            "When answering, refer to specific parts or quotes from the document where relevant."
        )

        formatted_history = ""
        if chat_history:
            history_lines = []
            for msg in chat_history[-6:]:  # include last 3 turns
                role = "User" if msg["role"] == "user" else "Assistant"
                history_lines.append(f"{role}: {msg['content']}")
            formatted_history = "--- PRIOR CONVERSATION ---\n" + "\n".join(history_lines) + "\n-------------------------\n"

        prompt = f"""
{formatted_history}

--- DOCUMENT CONTENT ---
{document_text}
--- END DOCUMENT CONTENT ---

USER QUESTION: {question}

Please provide a detailed, accurate response based on the document above.
"""
        return self._generate_text(prompt, system_instruction=system_instruction)

    def extract_insights(self, document_text: str) -> str:
        """
        Generate document analytical insights (Tone, Complexity, Audience, Key Themes).
        
        Args:
            document_text: Full document text context.
            
        Returns:
            Structured Markdown analytical breakdown.
        """
        system_instruction = "You are a document analytics expert evaluating text metadata and tone."

        prompt = f"""
Analyze the document below and output an Analytics Insight Report with the following sections:
- 📊 **Document Tone & Style**: (e.g. Formal, Academic, Technical, Persuasive, Conversational)
- 🎯 **Target Audience**: (e.g. Developers, Researchers, Executives, General Public)
- 🧠 **Complexity Level**: (e.g. Beginner, Intermediate, Advanced Technical, Expert)
- 💡 **Primary Purpose**: (e.g. Research Dissemination, Policy Guide, Technical Manual)
- 🔑 **Key Entities / Subject Areas**: Top 5 entity subjects discussed.

--- DOCUMENT CONTENT ---
{document_text}
--- END DOCUMENT CONTENT ---
"""
        return self._generate_text(prompt, system_instruction=system_instruction)
